
COCO_CATEGORIES = [
    {"id": 1, "name": "person"},
    {"id": 2, "name": "bicycle"},
    {"id": 3, "name": "car"},
    {"id": 4, "name": "motorcycle"},
    {"id": 5, "name": "airplane"},
    {"id": 6, "name": "bus"},
    {"id": 7, "name": "train"},
    {"id": 8, "name": "truck"},
    {"id": 9, "name": "boat"},
    {"id": 10, "name": "traffic light"},
    {"id": 11, "name": "fire hydrant"},
    {"id": 12, "name": "stop sign"},
    {"id": 13, "name": "parking meter"},
    {"id": 14, "name": "bench"},
    {"id": 15, "name": "bird"},
    {"id": 16, "name": "cat"},
    {"id": 17, "name": "dog"},
    {"id": 18, "name": "horse"},
    {"id": 19, "name": "sheep"},
    {"id": 20, "name": "cow"},
    {"id": 21, "name": "elephant"},
    {"id": 22, "name": "bear"},
    {"id": 23, "name": "zebra"},
    {"id": 24, "name": "giraffe"},
    {"id": 25, "name": "backpack"},
    {"id": 26, "name": "umbrella"},
    {"id": 27, "name": "handbag"},
    {"id": 28, "name": "tie"},
    {"id": 29, "name": "suitcase"},
    {"id": 30, "name": "frisbee"},
    {"id": 31, "name": "skis"},
    {"id": 32, "name": "snowboard"},
    {"id": 33, "name": "sports ball"},
    {"id": 34, "name": "kite"},
    {"id": 35, "name": "baseball bat"},
    {"id": 36, "name": "baseball glove"},
    {"id": 37, "name": "skateboard"},
    {"id": 38, "name": "surfboard"},
    {"id": 39, "name": "tennis racket"},
    {"id": 40, "name": "bottle"},
    {"id": 41, "name": "wine glass"},
    {"id": 42, "name": "cup"},
    {"id": 43, "name": "fork"},
    {"id": 44, "name": "knife"},
    {"id": 45, "name": "spoon"},
    {"id": 46, "name": "bowl"},
    {"id": 47, "name": "banana"},
    {"id": 48, "name": "apple"},
    {"id": 49, "name": "sandwich"},
    {"id": 50, "name": "orange"},
    {"id": 51, "name": "broccoli"},
    {"id": 52, "name": "carrot"},
    {"id": 53, "name": "hot dog"},
    {"id": 54, "name": "pizza"},
    {"id": 55, "name": "donut"},
    {"id": 56, "name": "cake"},
    {"id": 57, "name": "chair"},
    {"id": 58, "name": "couch"},
    {"id": 59, "name": "potted plant"},
    {"id": 60, "name": "bed"},
    {"id": 61, "name": "dining table"},
    {"id": 62, "name": "toilet"},
    {"id": 63, "name": "tv"},
    {"id": 64, "name": "laptop"},
    {"id": 65, "name": "mouse"},
    {"id": 66, "name": "remote"},
    {"id": 67, "name": "keyboard"},
    {"id": 68, "name": "cell phone"},
    {"id": 69, "name": "microwave"},
    {"id": 70, "name": "oven"},
    {"id": 71, "name": "toaster"},
    {"id": 72, "name": "sink"},
    {"id": 73, "name": "refrigerator"},
    {"id": 74, "name": "book"},
    {"id": 75, "name": "clock"},
    {"id": 76, "name": "vase"},
    {"id": 77, "name": "scissors"},
    {"id": 78, "name": "teddy bear"},
    {"id": 79, "name": "hair drier"},
    {"id": 80, "name": "toothbrush"},
    {"id": 81, "name": "banner"},
    {"id": 82, "name": "blanket"},
    {"id": 83, "name": "bridge"},
    {"id": 84, "name": "cardboard"},
    {"id": 85, "name": "counter"},
    {"id": 86, "name": "curtain"},
    {"id": 87, "name": "door-stuff"},
    {"id": 88, "name": "floor-wood"},
    {"id": 89, "name": "flower"},
    {"id": 90, "name": "fruit"},
    {"id": 91, "name": "gravel"},
    {"id": 92, "name": "house"},
    {"id": 93, "name": "light"},
    {"id": 94, "name": "mirror-stuff"},
    {"id": 95, "name": "net"},
    {"id": 96, "name": "pillow"},
    {"id": 97, "name": "platform"},
    {"id": 98, "name": "playingfield"},
    {"id": 99, "name": "railroad"},
    {"id": 100, "name": "river"},
    {"id": 101, "name": "road"},
    {"id": 102, "name": "roof"},
    {"id": 103, "name": "sand"},
    {"id": 104, "name": "sea"},
    {"id": 105, "name": "shelf"},
    {"id": 106, "name": "snow"},
    {"id": 107, "name": "stairs"},
    {"id": 108, "name": "tent"},
    {"id": 109, "name": "towel"},
    {"id": 110, "name": "wall-brick"},
    {"id": 111, "name": "wall-stone"},
    {"id": 112, "name": "wall-tile"},
    {"id": 113, "name": "wall-wood"},
    {"id": 114, "name": "water-other"},
    {"id": 115, "name": "window-blind"},
    {"id": 116, "name": "window-other"},
    {"id": 117, "name": "tree"},
    {"id": 118, "name": "fence"},
    {"id": 119, "name": "ceiling-other"},
    {"id": 120, "name": "ceiling-tile"},
    {"id": 121, "name": "cabinet"},
    {"id": 122, "name": "table"},
    {"id": 123, "name": "floor-other"},
    {"id": 124, "name": "pavement"},
    {"id": 125, "name": "mountain"},
    {"id": 126, "name": "grass"},
    {"id": 127, "name": "dirt"},
    {"id": 128, "name": "paper"},
    {"id": 129, "name": "food-other"},
    {"id": 130, "name": "building-other"},
    {"id": 131, "name": "rock"},
    {"id": 132, "name": "wall-other"},
    {"id": 133, "name": "rug"}
]
