name: CVENV
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pytorch==2.3.1
  - torchvision==0.18.1
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - transformers==4.56.0
    - addict==2.4.0
    - yapf==0.40.1
    - timm==1.0.19
    - numpy==1.26.4
    - opencv-python==4.6.0.66
    - supervision==0.26.1
    - pycocotools==2.0.10
    - requests==2.32.5
    - matplotlib==3.10.0
    - ipykernel 
    - ipywidgets
    - jupyter

# Note: The groundingdino package must be installed manually after the environment is created.
# Activate the conda environment, then run the following command from the GroundingDINO directory:
# pip install -e . --no-build-isolation
